name: Deploy

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        node: [ '16' ]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Export custom variables
        run: |
          SAFE_GITHUB_HEAD_REF_SLUG_URL=$(echo $GITHUB_HEAD_REF_SLUG_URL | rev | cut -c-37 | rev)
          ([[ $GITHUB_REF == 'refs/heads/master' ]] && echo "BRANCH_SLUG=master" || echo "BRANCH_SLUG=$SAFE_GITHUB_HEAD_REF_SLUG_URL") >> $GITHUB_ENV

      - name: Build
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - run: yarn --pure-lockfile
      - run: yarn run build
      - run: yarn run export

      - name: S3 Create Bucket
        uses: remyleone/scw-s3-action@v0.0.2
        with:
          args: s3 mb s3://${{ env.BRANCH_SLUG }}
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_REGION: 'fr-par'

      - name: Configure Bucket
        uses: remyleone/scw-s3-action@v0.0.2
        with:
          args: s3api put-bucket-website --bucket ${{ env.BRANCH_SLUG }} --website-configuration ./bucket-website.json
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_REGION: 'fr-par'

      - name: S3 Deploy
        uses: remyleone/scw-s3-action@v0.0.2
        with:
          args: s3 sync ./out s3://${{ env.BRANCH_SLUG }} --delete
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_REGION: 'fr-par'


