name: Deploy

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Export custom variables
        run: |
          SAFE_GITHUB_HEAD_REF_SLUG_URL=$(echo $GITHUB_HEAD_REF_SLUG_URL | rev | cut -c-37 | rev)
          ([[ $GITHUB_REF == 'refs/heads/main' ]] && echo "BRANCH_SLUG=main" || echo "BRANCH_SLUG=$SAFE_GITHUB_HEAD_REF_SLUG_URL") >> $GITHUB_ENV

      - name: Build
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      - run: yarn --pure-lockfile
      - run: yarn run build
      - run: yarn run export

      - name: Start deployment
        uses: bobheadxi/deployments@v0.6.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.BRANCH_SLUG }}
          ref: ${{ github.head_ref }}

      - name: S3 Create Bucket
        uses: remyleone/scw-s3-action@v0.0.2
        with:
          args: s3 mb s3://${{ env.BRANCH_SLUG }}
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_REGION: 'fr-par'

      - name: S3 Enable Bucket Website
        uses: remyleone/scw-s3-action@v0.0.2
        with:
          args: s3api put-bucket-website --bucket ${{ env.BRANCH_SLUG }} --website-configuration file://.bucket-website.json
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_REGION: 'fr-par'
        if: success()

      - name: Configure Bucket Policies
        run: sed -e "s/BUCKET_NAME/${{ env.BRANCH_SLUG }}/g" ./bucket-policy.json.tpl > bucket-policy.json
        if: success()

      - name: S3 Set Bucket Policies
        uses: remyleone/scw-s3-action@v0.0.2
        with:
          args: s3api put-bucket-policy --bucket ${{ env.BRANCH_SLUG }} --policy file://bucket-policy.json
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_REGION: 'fr-par'
        if: success()

      - name: S3 Deploy
        uses: remyleone/scw-s3-action@v0.0.2
        with:
          args: s3 sync ./out s3://${{ env.BRANCH_SLUG }} --delete
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_REGION: 'fr-par'
        if: always()

      - name: Update deployment status
        uses: bobheadxi/deployments@v0.6.0
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ env.BRANCH_SLUG }}.s3-website.fr-par.scw.cloud
        if: always()

  lighthouse:
    runs-on: self-hosted
    needs: [ deploy ]
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Export custom variables
        run: |
          SAFE_GITHUB_HEAD_REF_SLUG_URL=$(echo $GITHUB_HEAD_REF_SLUG_URL | rev | cut -c-37 | rev)
          ([[ $GITHUB_REF == 'refs/heads/main' ]] && echo "BRANCH_SLUG=main" || echo "BRANCH_SLUG=$SAFE_GITHUB_HEAD_REF_SLUG_URL") >> $GITHUB_ENV
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://${{ env.BRANCH_SLUG }}.s3-website.fr-par.scw.cloud
          serverBaseUrl: ${{ secrets.LHCI_SERVER_BASE_URL }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}
          configPath: './.lighthouserc.json'


